package ch.arkeine.smartgm.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig universesDaoConfig;
    private final DaoConfig gamesDaoConfig;
    private final DaoConfig wikisDaoConfig;
    private final DaoConfig timelinesDaoConfig;
    private final DaoConfig tablesDaoConfig;
    private final DaoConfig tableitemsDaoConfig;
    private final DaoConfig dicesDaoConfig;

    private final UniversesDao universesDao;
    private final GamesDao gamesDao;
    private final WikisDao wikisDao;
    private final TimelinesDao timelinesDao;
    private final TablesDao tablesDao;
    private final TableitemsDao tableitemsDao;
    private final DicesDao dicesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        universesDaoConfig = daoConfigMap.get(UniversesDao.class).clone();
        universesDaoConfig.initIdentityScope(type);

        gamesDaoConfig = daoConfigMap.get(GamesDao.class).clone();
        gamesDaoConfig.initIdentityScope(type);

        wikisDaoConfig = daoConfigMap.get(WikisDao.class).clone();
        wikisDaoConfig.initIdentityScope(type);

        timelinesDaoConfig = daoConfigMap.get(TimelinesDao.class).clone();
        timelinesDaoConfig.initIdentityScope(type);

        tablesDaoConfig = daoConfigMap.get(TablesDao.class).clone();
        tablesDaoConfig.initIdentityScope(type);

        tableitemsDaoConfig = daoConfigMap.get(TableitemsDao.class).clone();
        tableitemsDaoConfig.initIdentityScope(type);

        dicesDaoConfig = daoConfigMap.get(DicesDao.class).clone();
        dicesDaoConfig.initIdentityScope(type);

        universesDao = new UniversesDao(universesDaoConfig, this);
        gamesDao = new GamesDao(gamesDaoConfig, this);
        wikisDao = new WikisDao(wikisDaoConfig, this);
        timelinesDao = new TimelinesDao(timelinesDaoConfig, this);
        tablesDao = new TablesDao(tablesDaoConfig, this);
        tableitemsDao = new TableitemsDao(tableitemsDaoConfig, this);
        dicesDao = new DicesDao(dicesDaoConfig, this);

        registerDao(Universes.class, universesDao);
        registerDao(Games.class, gamesDao);
        registerDao(Wikis.class, wikisDao);
        registerDao(Timelines.class, timelinesDao);
        registerDao(Tables.class, tablesDao);
        registerDao(Tableitems.class, tableitemsDao);
        registerDao(Dices.class, dicesDao);
    }
    
    public void clear() {
        universesDaoConfig.getIdentityScope().clear();
        gamesDaoConfig.getIdentityScope().clear();
        wikisDaoConfig.getIdentityScope().clear();
        timelinesDaoConfig.getIdentityScope().clear();
        tablesDaoConfig.getIdentityScope().clear();
        tableitemsDaoConfig.getIdentityScope().clear();
        dicesDaoConfig.getIdentityScope().clear();
    }

    public UniversesDao getUniversesDao() {
        return universesDao;
    }

    public GamesDao getGamesDao() {
        return gamesDao;
    }

    public WikisDao getWikisDao() {
        return wikisDao;
    }

    public TimelinesDao getTimelinesDao() {
        return timelinesDao;
    }

    public TablesDao getTablesDao() {
        return tablesDao;
    }

    public TableitemsDao getTableitemsDao() {
        return tableitemsDao;
    }

    public DicesDao getDicesDao() {
        return dicesDao;
    }

}
