package ch.arkeine.smartgm.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DICES".
*/
public class DicesDao extends AbstractDao<Dices, Long> {

    public static final String TABLENAME = "DICES";

    /**
     * Properties of entity Dices.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Face = new Property(1, Integer.class, "face", false, "FACE");
        public final static Property Count = new Property(2, Integer.class, "count", false, "COUNT");
        public final static Property Fk_universe_id = new Property(3, Long.class, "fk_universe_id", false, "FK_UNIVERSE_ID");
    };

    private DaoSession daoSession;

    private Query<Dices> universes_DicesQuery;

    public DicesDao(DaoConfig config) {
        super(config);
    }
    
    public DicesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DICES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FACE\" INTEGER," + // 1: face
                "\"COUNT\" INTEGER," + // 2: count
                "\"FK_UNIVERSE_ID\" INTEGER);"); // 3: fk_universe_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DICES\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Dices entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer face = entity.getFace();
        if (face != null) {
            stmt.bindLong(2, face);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(3, count);
        }
 
        Long fk_universe_id = entity.getFk_universe_id();
        if (fk_universe_id != null) {
            stmt.bindLong(4, fk_universe_id);
        }
    }

    @Override
    protected void attachEntity(Dices entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Dices readEntity(Cursor cursor, int offset) {
        Dices entity = new Dices( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // face
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // count
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // fk_universe_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Dices entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFace(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setCount(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setFk_universe_id(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Dices entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Dices entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "dices" to-many relationship of Universes. */
    public List<Dices> _queryUniverses_Dices(Long fk_universe_id) {
        synchronized (this) {
            if (universes_DicesQuery == null) {
                QueryBuilder<Dices> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Fk_universe_id.eq(null));
                universes_DicesQuery = queryBuilder.build();
            }
        }
        Query<Dices> query = universes_DicesQuery.forCurrentThread();
        query.setParameter(0, fk_universe_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUniversesDao().getAllColumns());
            builder.append(" FROM DICES T");
            builder.append(" LEFT JOIN UNIVERSES T0 ON T.\"FK_UNIVERSE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Dices loadCurrentDeep(Cursor cursor, boolean lock) {
        Dices entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Universes universes = loadCurrentOther(daoSession.getUniversesDao(), cursor, offset);
        entity.setUniverses(universes);

        return entity;    
    }

    public Dices loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Dices> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Dices> list = new ArrayList<Dices>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Dices> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Dices> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
