package ch.arkeine.smartgm.model;

import java.util.List;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TABLES".
 */
public class Tables {

    private Long id;
    private java.util.Date name;
    private String description;
    private Long fk_universe_id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TablesDao myDao;

    private Universes universes;
    private Long universes__resolvedKey;

    private List<Tableitems> tableitem;

    public Tables() {
    }

    public Tables(Long id) {
        this.id = id;
    }

    public Tables(Long id, java.util.Date name, String description, Long fk_universe_id) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.fk_universe_id = fk_universe_id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTablesDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getName() {
        return name;
    }

    public void setName(java.util.Date name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getFk_universe_id() {
        return fk_universe_id;
    }

    public void setFk_universe_id(Long fk_universe_id) {
        this.fk_universe_id = fk_universe_id;
    }

    /** To-one relationship, resolved on first access. */
    public Universes getUniverses() {
        Long __key = this.fk_universe_id;
        if (universes__resolvedKey == null || !universes__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            UniversesDao targetDao = daoSession.getUniversesDao();
            Universes universesNew = targetDao.load(__key);
            synchronized (this) {
                universes = universesNew;
            	universes__resolvedKey = __key;
            }
        }
        return universes;
    }

    public void setUniverses(Universes universes) {
        synchronized (this) {
            this.universes = universes;
            fk_universe_id = universes == null ? null : universes.getId();
            universes__resolvedKey = fk_universe_id;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Tableitems> getTableitem() {
        if (tableitem == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TableitemsDao targetDao = daoSession.getTableitemsDao();
            List<Tableitems> tableitemNew = targetDao._queryTables_Tableitem(id);
            synchronized (this) {
                if(tableitem == null) {
                    tableitem = tableitemNew;
                }
            }
        }
        return tableitem;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetTableitem() {
        tableitem = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
